In [1]:
import numpy as np

In [2]:
import numpy as np
X_test = np.load("X_test.npy")
y_test = np.load("y_test.npy")
person_train_valid = np.load("person_train_valid.npy")
X_train_valid = np.load("X_train_valid.npy")
y_train_valid = np.load("y_train_valid.npy")
person_test = np.load("person_test.npy")


### Shape of data

In [3]:
print ('Training/Valid data shape: {}'.format(X_train_valid.shape))
print ('Test data shape: {}'.format(X_test.shape))
print ('Training/Valid target shape: {}'.format(y_train_valid.shape))
print ('Test target shape: {}'.format(y_test.shape))
print ('Person train/valid shape: {}'.format(person_train_valid.shape))
print ('Person test shape: {}'.format(person_test.shape))


Training/Valid data shape: (2115, 22, 1000)
Test data shape: (443, 22, 1000)
Training/Valid target shape: (2115,)
Test target shape: (443,)
Person train/valid shape: (2115, 1)
Person test shape: (443, 1)


In [4]:
print(y_test)

[770 769 771 772 772 771 771 772 772 769 771 772 771 769 770 770 772 772
 771 769 771 770 769 770 772 771 769 770 770 772 771 771 770 770 771 769
 769 769 769 772 770 771 769 770 772 771 769 772 771 770 770 771 769 772
 772 770 770 772 772 771 770 770 772 770 769 770 770 770 771 769 769 770
 772 771 771 769 770 771 769 771 772 771 769 770 772 769 769 772 772 769
 772 771 770 770 769 771 769 772 770 772 770 769 769 770 771 769 769 772
 771 771 772 770 772 770 769 769 770 772 770 769 769 769 772 771 772 769
 772 769 771 772 771 770 772 770 770 772 769 770 772 769 769 771 771 769
 771 772 772 770 769 772 769 772 770 771 770 769 771 769 770 772 769 770
 771 771 770 771 772 770 769 772 770 770 770 772 771 769 770 771 770 772
 771 772 772 770 770 772 770 771 771 770 772 771 772 772 771 771 770 772
 771 770 772 770 769 769 772 771 769 769 769 772 772 771 769 770 769 771
 769 769 772 771 770 770 772 770 769 771 769 770 771 772 770 770 771 769
 769 770 769 772 772 772 771 769 769 770 770 772 76

In [5]:
print(y_train_valid)

[771 772 769 ... 772 772 771]


In [6]:
print(max(y_train_valid))
print(min(y_train_valid))
print(max(y_test))
print(min(y_test))

772
769
772
769


In [7]:
print(person_train_valid)

[[0.]
 [0.]
 [0.]
 ...
 [8.]
 [8.]
 [8.]]


In [17]:
cnt = 0
for i in range(0,2115): 
    if person_train_valid[i] == 8:
        cnt = cnt+1
print(cnt)

231


In [18]:
print(person_test)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [2.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.]
 [3.